version: '3.8'

services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    env_file:
      - ./mern/backend/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./mern/frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:5173" # Map container port 5173 to localhost:3000
    networks:
      - mern_network
    volumes:
      - ./mern/frontend:/app:delegated # Sync the local frontend directory with the container
      - /app/node_modules             # Exclude node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true      # Enable polling for file changes    # Enable polling for file changes


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
