# Use the official Node.js 20 Alpine image
FROM node:22.11.0-alpine AS base

# Set the working directory inside the container
WORKDIR /app

# Copy package manager lock files and package.json
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./

# Install dependencies based on the available lockfile
RUN \
  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --frozen-lockfile; \
  else echo "No lockfile found. Exiting." && exit 1; \
  fi

# Copy the rest of the application code
COPY . .

# Expose the port that the application will use
EXPOSE 5173

# Use a simple inline start script to avoid creating unnecessary files
CMD ["sh", "-c", "\
  if [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm dev; \
  else echo 'No lockfile found. Exiting.' && exit 1; \
  fi"]
